#!/usr/bin/env bash
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
echo $SCRIPT_DIR
docker run -it --rm -p 8081:8080 -v $SCRIPT_DIR/dsl:/usr/local/structurizr structurizr/lite